version: 1.0.{build}
configuration: Debug
platform: Any CPU
image: Visual Studio 2017
install:
- git submodule update --init --recursive
- git clone https://github.com/icsharpcode/ILSpy-tests
before_build:
- nuget restore ILSpy.sln
build:
  parallel: false
  verbosity: minimal
build_script:
- devenv.exe "ILSpy.sln" /build Debug
test:
  assemblies:
    - 'ICSharpCode.Decompiler\bin\Debug\ICSharpCode.Decompiler.Tests.dll'
    - 'ILSpy.BamlDecompiler\bin\Debug\ILSpy.BamlDecompiler.Tests.dll'
after_test:
- python BuildTools\tidy.py
